"""Isaac Lab ArticulationCfg for Open Duck Mini V2.

Actuator gains are the ACTIVE `sts3215` class values from
Open_Duck_Playground's `xmls/open_duck_mini_v2.xml` (i.e. what the current
MJX-trained policy is actually tuned against) — see docs/decisions.md for
why these numbers were chosen over the other candidate value sets found in
the codebase (the abandoned Isaac Lab WIP's XM430 numbers, and
mini_bdx/robots/open_duck_mini_v2/robot.xml's alternate values).

USD path: generated by scripts/convert_urdf.sh from
assets/robot/open_duck_mini_v2/robot.urdf via IsaacLab's UrdfConverter.
Does NOT exist until that script has been run on a machine with Isaac Sim.
"""

import os

import isaaclab.sim as sim_utils
from isaaclab.actuators import ImplicitActuatorCfg
from isaaclab.assets.articulation import ArticulationCfg

from .joint_order import (
    ACTUATOR_JOINT_NAMES,
    HOME_BASE_HEIGHT,
    HOME_JOINT_POS,
)

# Resolved relative to this repo's root, so the config works regardless of
# where the repo is checked out on the training machine.
_REPO_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
OPEN_DUCK_MINI_USD_PATH = os.path.join(_REPO_ROOT, "assets", "usd", "open_duck_mini_v2.usd")

# Leg joints (10): position-servo STS3215, this exact set drives locomotion.
_LEG_JOINT_NAMES = [n for n in ACTUATOR_JOINT_NAMES if "hip" in n or "knee" in n or "ankle" in n]
# Head joints (4): same physical servo, but not part of the imitation reward
# and given a commanded (not learned) target — see reward docs.
_HEAD_JOINT_NAMES = [n for n in ACTUATOR_JOINT_NAMES if n not in _LEG_JOINT_NAMES]

assert set(_LEG_JOINT_NAMES) | set(_HEAD_JOINT_NAMES) == set(ACTUATOR_JOINT_NAMES)
assert len(_LEG_JOINT_NAMES) == 10 and len(_HEAD_JOINT_NAMES) == 4

##
# Actuator config — single STS3215 servo class covers all 14 actuated joints
# (Playground uses the same gains for legs and head; kept as one group here
# for the same reason, but split into two ActuatorBaseCfg entries only
# because Isaac Lab groups actuators by joint_names_expr, not because the
# physical gains differ).
##

STS3215_LEG_CFG = ImplicitActuatorCfg(
    joint_names_expr=_LEG_JOINT_NAMES,
    stiffness=13.37,
    damping=0.56,
    armature=0.027,
    friction=0.068,
    effort_limit_sim=3.23,
    velocity_limit_sim=5.24,
)

STS3215_HEAD_CFG = ImplicitActuatorCfg(
    joint_names_expr=_HEAD_JOINT_NAMES,
    stiffness=13.37,
    damping=0.56,
    armature=0.027,
    friction=0.068,
    effort_limit_sim=3.23,
    velocity_limit_sim=5.24,
)

##
# Robot config
##

OPEN_DUCK_MINI_V2_CFG = ArticulationCfg(
    spawn=sim_utils.UsdFileCfg(
        usd_path=OPEN_DUCK_MINI_USD_PATH,
        activate_contact_sensors=True,
        rigid_props=sim_utils.RigidBodyPropertiesCfg(
            disable_gravity=False,
            retain_accelerations=False,
            linear_damping=0.0,
            angular_damping=0.0,
            max_linear_velocity=1000.0,
            max_angular_velocity=1000.0,
            max_depenetration_velocity=1.0,
        ),
        articulation_props=sim_utils.ArticulationRootPropertiesCfg(
            enabled_self_collisions=False,
            solver_position_iteration_count=4,
            solver_velocity_iteration_count=0,
        ),
    ),
    init_state=ArticulationCfg.InitialStateCfg(
        pos=(0.0, 0.0, HOME_BASE_HEIGHT),
        joint_pos=dict(HOME_JOINT_POS),
        joint_vel={".*": 0.0},
    ),
    soft_joint_pos_limit_factor=0.95,
    actuators={
        "legs": STS3215_LEG_CFG,
        "head": STS3215_HEAD_CFG,
    },
)
