"""Isaac Lab ArticulationCfg for Open Duck Mini V2.

This robot's actual actuator is a Dynamixel XM430 (confirmed choice for the
rebuild — see docs/onshape_import.md), not the original project's STS3215.
Actuator gains below are sourced from the "m4"-model BAM characterization at
~/Desktop/robot make/bam_xm430_params/m4.json:

  armature = 0.014317492733137276  (BAM "armature", direct)
  friction = 0.07610030458666567   (BAM "friction_base" — the Coulomb/base
                                     term only. BAM's m4 model is a full
                                     Stribeck friction curve — friction_base,
                                     friction_stribeck, load_friction_base,
                                     load_friction_stribeck, dtheta_stribeck,
                                     alpha — but ImplicitActuatorCfg.friction
                                     is a single scalar, so only the base term
                                     maps here. The velocity- and
                                     load-dependent terms have no home in this
                                     actuator model.)

stiffness and damping (2026-07-26, superseding an earlier STS3215-leftover
13.37/BAM-friction-viscous-only 0.847 pair) are derived from BAM's own
position-actuator conversion, `VoltageControlledActuator.to_mujoco()` in
bam/bam/actuator.py — NOT a dead end as first assessed; that method exists
specifically to turn BAM's fitted electrical/friction model plus the servo's
real Position P Gain register setting into physical PD gains:

  stiffness = error_gain * kp_register * vin * max_pwm * kt / R
            = (1/128)    * 800.0       * 12.0 * 1.0     * 1.0057156607538362 / 2.0032635699956667
            = 37.6528958476996   ->  37.65

  damping   = friction_viscous + kt**2 / R
            = 0.8470782260272692 + 1.0057156607538362**2 / 2.0032635699956667
            = 1.3519863197174637 -> 1.352
            (friction_viscous alone, used previously, omits the back-EMF
             term kt**2/R that to_mujoco() includes — that was also wrong,
             not just stiffness)

  where kt, R, friction_viscous are BAM's fit for our actual characterized
  unit (m4.json); error_gain=1/128 is the XM430 Position P Gain register
  conversion (hardcoded in bam/bam/dynamixel/actuator.py's XM430Actuator,
  matches the ROBOTIS datasheet formula Kp_actual=Kp_TBL/128); kp_register=
  800.0 is the servo's factory-default Position P Gain (also XM430Actuator's
  constructor default) — CONFIRMED 2026-07-26 by reading the actual control
  table off the real hardware (Dynamixel Wizard: Position P Gain=800/0x0320,
  Velocity P/I Gain=100/1920 matching datasheet defaults too, Voltage=12.20V
  matching the assumed 12.0V), not just assumed to match what was on the
  servo during the m4.json data collection. vin=12.0 is the confirmed
  operating voltage; max_pwm=1.0 is BAM's default (no duty-cycle cap
  configured for this unit).

  Cross-check: independently, IsaacLab GitHub Discussion #2627 (XM430-W350
  PD tuning for the Robotis OP3, unresolved thread, no official derivation)
  reports stiffness=45.0/damping=1.5 as values someone tried — same order of
  magnitude as the BAM-derived numbers above, though that thread's values
  aren't independently validated either. The BAM-derived numbers here are
  preferred since they come from measurements of our own physical unit, not
  a different robot's community trial-and-error.

Sourced from the ROBOTIS XM430-W350 datasheet instead of BAM (m4.json has no
torque/speed limit fields), at the confirmed operating voltage of 12.0V —
https://docs.robotis.com/docs/dxl/model_reference/x_series/xm_series/xm430-w350 :

  effort_limit_sim   = 4.1   (N*m)   — stall torque @ 12.0V, 2.3A
  velocity_limit_sim = 4.82  (rad/s) — no-load speed @ 12.0V, 46 rpm -> rad/s

NOT sourced from either BAM or the datasheet:
  q_offset  — BAM's fitted joint zero-offset for the one physical unit on the
              test rig, not a per-robot design value; intentionally not
              applied anywhere.

USD path: generated by scripts/convert_urdf.sh from robot/robot.urdf (see
docs/onshape_import.md) via IsaacLab's UrdfConverter. Does NOT exist until
that script has been run on a machine with Isaac Sim.
"""

import os

import isaaclab.sim as sim_utils
from isaaclab.actuators import ImplicitActuatorCfg
from isaaclab.assets.articulation import ArticulationCfg

from .joint_order import (
    ACTUATOR_JOINT_NAMES,
    HOME_BASE_HEIGHT,
    HOME_JOINT_POS,
)

# Resolved relative to this repo's root, so the config works regardless of
# where the repo is checked out on the training machine.
_REPO_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
OPEN_DUCK_MINI_USD_PATH = os.path.join(_REPO_ROOT, "robot", "usd", "open_duck_mini_v2.usd")

# Leg joints (10): position-servo XM430, this exact set drives locomotion.
_LEG_JOINT_NAMES = [n for n in ACTUATOR_JOINT_NAMES if "hip" in n or "knee" in n or "ankle" in n]
# Head joints (4): same physical servo, but not part of the imitation reward
# and given a commanded (not learned) target — see reward docs.
_HEAD_JOINT_NAMES = [n for n in ACTUATOR_JOINT_NAMES if n not in _LEG_JOINT_NAMES]

assert set(_LEG_JOINT_NAMES) | set(_HEAD_JOINT_NAMES) == set(ACTUATOR_JOINT_NAMES)
assert len(_LEG_JOINT_NAMES) == 10 and len(_HEAD_JOINT_NAMES) == 4

##
# Actuator config — single XM430 servo class covers all 14 actuated joints
# (kept as one group here since gains don't differ between legs/head, split
# into two ActuatorBaseCfg entries only because Isaac Lab groups actuators by
# joint_names_expr).
##

XM430_LEG_CFG = ImplicitActuatorCfg(
    joint_names_expr=_LEG_JOINT_NAMES,
    stiffness=37.65,
    damping=1.352,
    armature=0.01432,
    friction=0.0761,
    effort_limit_sim=4.1,
    velocity_limit_sim=4.82,
)

XM430_HEAD_CFG = ImplicitActuatorCfg(
    joint_names_expr=_HEAD_JOINT_NAMES,
    stiffness=37.65,
    damping=1.352,
    armature=0.01432,
    friction=0.0761,
    effort_limit_sim=4.1,
    velocity_limit_sim=4.82,
)

##
# Robot config
##

OPEN_DUCK_MINI_V2_CFG = ArticulationCfg(
    spawn=sim_utils.UsdFileCfg(
        usd_path=OPEN_DUCK_MINI_USD_PATH,
        activate_contact_sensors=True,
        rigid_props=sim_utils.RigidBodyPropertiesCfg(
            disable_gravity=False,
            retain_accelerations=False,
            linear_damping=0.0,
            angular_damping=0.0,
            max_linear_velocity=1000.0,
            max_angular_velocity=1000.0,
            max_depenetration_velocity=1.0,
        ),
        articulation_props=sim_utils.ArticulationRootPropertiesCfg(
            enabled_self_collisions=False,
            solver_position_iteration_count=4,
            solver_velocity_iteration_count=0,
        ),
    ),
    init_state=ArticulationCfg.InitialStateCfg(
        pos=(0.0, 0.0, HOME_BASE_HEIGHT),
        joint_pos=dict(HOME_JOINT_POS),
        joint_vel={".*": 0.0},
    ),
    soft_joint_pos_limit_factor=0.95,
    actuators={
        "legs": XM430_LEG_CFG,
        "head": XM430_HEAD_CFG,
    },
)
