"""Isaac Lab ArticulationCfg for Open Duck Mini V2.

This robot's actual actuator is a Dynamixel XM430 (confirmed choice for the
rebuild — see docs/onshape_import.md), not the original project's STS3215.
Actuator gains below are sourced from the "m4"-model BAM characterization at
~/Desktop/robot make/bam_xm430_params/m4.json:

  armature = 0.014317492733137276  (BAM "armature", direct)
  friction = 0.07610030458666567   (BAM "friction_base" — the Coulomb/base
                                     term only. BAM's m4 model is a full
                                     Stribeck friction curve — friction_base,
                                     friction_stribeck, load_friction_base,
                                     load_friction_stribeck, dtheta_stribeck,
                                     alpha — but ImplicitActuatorCfg.friction
                                     is a single scalar, so only the base term
                                     maps here. The velocity- and
                                     load-dependent terms have no home in this
                                     actuator model.)

stiffness and damping (2026-07-26, superseding an earlier STS3215-leftover
13.37/BAM-friction-viscous-only 0.847 pair) are derived from BAM's own
position-actuator conversion, `VoltageControlledActuator.to_mujoco()` in
bam/bam/actuator.py — NOT a dead end as first assessed; that method exists
specifically to turn BAM's fitted electrical/friction model plus the servo's
real Position P Gain register setting into physical PD gains:

  stiffness = error_gain * kp_register * vin * max_pwm * kt / R
            = (1/128)    * 800.0       * 12.0 * 1.0     * 1.0057156607538362 / 2.0032635699956667
            = 37.6528958476996   ->  37.65

  damping   = friction_viscous + kt**2 / R
            = 0.8470782260272692 + 1.0057156607538362**2 / 2.0032635699956667
            = 1.3519863197174637 -> 1.352
            (friction_viscous alone, used previously, omits the back-EMF
             term kt**2/R that to_mujoco() includes — that was also wrong,
             not just stiffness)

  where kt, R, friction_viscous are BAM's fit for our actual characterized
  unit (m4.json); error_gain=1/128 is the XM430 Position P Gain register
  conversion (hardcoded in bam/bam/dynamixel/actuator.py's XM430Actuator,
  matches the ROBOTIS datasheet formula Kp_actual=Kp_TBL/128); kp_register=
  800.0 is the servo's factory-default Position P Gain (also XM430Actuator's
  constructor default) — CONFIRMED 2026-07-26 by reading the actual control
  table off the real hardware (Dynamixel Wizard: Position P Gain=800/0x0320,
  Velocity P/I Gain=100/1920 matching datasheet defaults too, Voltage=12.20V
  matching the assumed 12.0V), not just assumed to match what was on the
  servo during the m4.json data collection. vin=12.0 is the confirmed
  operating voltage; max_pwm=1.0 is BAM's default (no duty-cycle cap
  configured for this unit).

  Cross-check: independently, IsaacLab GitHub Discussion #2627 (XM430-W350
  PD tuning for the Robotis OP3, unresolved thread, no official derivation)
  reports stiffness=45.0/damping=1.5 as values someone tried — same order of
  magnitude as the BAM-derived numbers above, though that thread's values
  aren't independently validated either. The BAM-derived numbers here are
  preferred since they come from measurements of our own physical unit, not
  a different robot's community trial-and-error.

Sourced from the ROBOTIS XM430-W350 datasheet instead of BAM (m4.json has no
torque/speed limit fields), at the confirmed operating voltage of 12.0V —
https://docs.robotis.com/docs/dxl/model_reference/x_series/xm_series/xm430-w350 :

  effort_limit_sim   = 4.1   (N*m)   — stall torque @ 12.0V, 2.3A
  velocity_limit_sim = 4.82  (rad/s) — no-load speed @ 12.0V, 46 rpm -> rad/s

NOT sourced from either BAM or the datasheet:
  q_offset  — BAM's fitted joint zero-offset for the one physical unit on the
              test rig, not a per-robot design value; intentionally not
              applied anywhere.

USD path: generated by scripts/convert_urdf.sh from robot/robot.urdf (see
docs/onshape_import.md) via IsaacLab's UrdfConverter. Does NOT exist until
that script has been run on a machine with Isaac Sim.
"""

import os

import isaaclab.sim as sim_utils
from isaaclab.actuators import DCMotorCfg, ImplicitActuatorCfg
from isaaclab.assets.articulation import ArticulationCfg

from .joint_order import (
    ACTUATOR_JOINT_NAMES,
    SPAWN_BASE_HEIGHT,
    READY_JOINT_POS,
)

# Resolved relative to this repo's root, so the config works regardless of
# where the repo is checked out on the training machine.
_REPO_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
OPEN_DUCK_MINI_USD_PATH = os.path.join(_REPO_ROOT, "robot", "usd", "open_duck_mini_v2.usd")
#: 발바닥 접지면을 키운 변형 (2026-08-20). 운동학은 기존과 **완전 동일**하다
#: (14 축 부모·자식·축·rpy·xyz·한계 전부 일치, -0/0 표기 차이만 있음).
#: 질량 차이: 발 편측 69.5 -> 79.9 g, 그리고 몸통 1165.0 -> 1153.0 g
#: (릴레이를 실기에서 뺀 것이 반영됐다). 총 2743.0 -> 2751.8 g.
#:
#: **심이 실제로 딛는 면**은 TPU 밑창이 아니라 `l_foot_side` 다 — TPU 는 그보다
#: 2.70 mm 위라 지면에 닿지 않는다. 링크 좌표계 실측(지면 ±0.2 mm 삼각형):
#:     기존      1907 mm^2   전후  99.3 mm   좌우 38.7 mm
#:     big_foot  2365 mm^2   전후 108.6 mm   좌우 42.9 mm
#: 즉 심의 좌우 지지는 +11 % 만 는다. STL 만 보고 적었던 "16.3 -> 40.0 mm,
#: 2.5 배" 는 TPU 단독 치수였고 심에는 해당하지 않는다.
#: onshape-to-robot 산출물은 big_foot/ 에 그대로 두고 USD 도 그 안에 만든다 —
#: 한 번의 import 에서 나온 것(URDF·메시·USD)을 한 디렉터리에 모으는 규칙.
OPEN_DUCK_MINI_BIGFOOT_USD_PATH = os.path.join(
    _REPO_ROOT, "big_foot", "usd", "open_duck_mini_v2_bigfoot.usd")

# Leg joints (10): position-servo XM430, this exact set drives locomotion.
_LEG_JOINT_NAMES = [n for n in ACTUATOR_JOINT_NAMES if "hip" in n or "knee" in n or "ankle" in n]
# Head joints (4): same physical servo, but not part of the imitation reward
# and given a commanded (not learned) target — see reward docs.
_HEAD_JOINT_NAMES = [n for n in ACTUATOR_JOINT_NAMES if n not in _LEG_JOINT_NAMES]

assert set(_LEG_JOINT_NAMES) | set(_HEAD_JOINT_NAMES) == set(ACTUATOR_JOINT_NAMES)
assert len(_LEG_JOINT_NAMES) == 10 and len(_HEAD_JOINT_NAMES) == 4

##
# Actuator config — single XM430 servo class covers all 14 actuated joints
# (kept as one group here since gains don't differ between legs/head, split
# into two ActuatorBaseCfg entries only because Isaac Lab groups actuators by
# joint_names_expr).
##

XM430_LEG_CFG = ImplicitActuatorCfg(
    joint_names_expr=_LEG_JOINT_NAMES,
    stiffness=37.65,
    damping=1.352,
    armature=0.01432,
    friction=0.0761,
    effort_limit_sim=4.1,
    velocity_limit_sim=4.82,
)

XM430_HEAD_CFG = ImplicitActuatorCfg(
    joint_names_expr=_HEAD_JOINT_NAMES,
    stiffness=37.65,
    damping=1.352,
    armature=0.01432,
    friction=0.0761,
    effort_limit_sim=4.1,
    velocity_limit_sim=4.82,
)

##
# DC 모터 변형 (2026-08-10, v41) — 토크-속도 직선을 넣는다.
#
# 위 ImplicitActuatorCfg 는 effort_limit 과 velocity_limit 을 **서로 독립으로**
# 건다. 그래서 심의 다리는 "4.1 N·m 를 내면서 동시에 4.82 rad/s 로" 움직일 수
# 있는데, 실제 DC 모터는 그 조합을 못 낸다 — 토크가 오르면 속도가 떨어진다.
#
# 2026-08-10 실기 로그가 이 갭을 정확히 짚었다 (docs/reports/
# hw_v40_followup_2026-08-10.md §3). 전류 상한을 700 틱으로 올려 토크 포화를
# 0 % 로 없앤 뒤에도 무릎·고관절이 지령 속도를 못 따라갔다:
#
#     관절              지령 p95   실측 최대
#     left_knee           4.84       3.53
#     right_knee          5.17       3.98
#     left_hip_pitch      4.66       3.72
#
# 같은 무릎이 **무부하** 계단시험에서는 4.41 rad/s (무부하 한계의 92 %) 를 낸다.
# 부하가 걸릴 때만 막히므로 토크-속도 직선이다. 뒤처지는 축들은 직선 사용률이
# 81~99 % 인 반면, 오차가 거의 없는 hip_yaw 두 축은 51 / 57 % 다.
#
# IsaacLab 의 DCMotor 가 정확히 그 직선을 구현한다
# (actuators/actuator_pd.py `_clip_effort`):
#     torque_speed_top = saturation_effort * (1 - joint_vel / velocity_limit)
#
# stiffness/damping/armature/friction 은 **건드리지 않는다.** 37.65 는 실기
# 서보의 Position P Gain 레지스터 800 을 그대로 넣어 BAM 실측 kt/R 로 유도한
# 값이고 (위 헤더 주석), 실기에서 읽은 P/I/D 도 다리 전 축 800/0/4700 이다.
#
# 주의: DCMotor 는 **명시적(explicit) 액추에이터**라 PD 계산이 PhysX 에서
# 파이썬으로 옮겨온다. 그래서 여기서는 `effort_limit`/`velocity_limit`(모델용)
# 을 쓴다 — `*_limit_sim` 은 암시적 액추에이터가 PhysX 에 넘기는 값이라 의미가
# 다르다.
##

#: 스톨 토크 (N·m) — 무부하 속도 0 에서의 최대 토크. XM430-W350 @ 12 V.
XM430_STALL_TORQUE = 4.1
#: 무부하 속도 (rad/s) — 토크 0 에서의 최대 속도.
XM430_NO_LOAD_SPEED = 4.82
#: 전류 상한이 잘라내는 연속 토크 (N·m).
#: 실기 Goal Current 를 **700 틱** × 2.69 mA = 1.883 A 로 두었을 때의 값.
#:
#: ⚠️ 이건 심이 실기에 요구하는 **계약**이지 실기가 알아서 그렇게 도는 게
#: 아니다. 2026-08-12 에 실기 컨트롤 테이블을 처음 덤프해 보니 Goal Current
#: 가 **350 틱 (0.94 A → 1.32 N·m)** 이었다 — 심이 가정한 토크의 42 %.
#: `rl_walk.py --current` 기본값이 350 이었던 탓이다. 심 정책은 무릎에
#: 3.16 N·m 를 쓸 수 있다고 배웠는데 실기는 1.32 N·m 에서 잘렸으니 체중을
#: 받는 순간 무릎이 밀려 내려간다. 기본값을 700 으로 고쳤다.
#: 이 상수를 바꾸면 `rl_walk.py --current` 도 같이 바꿔야 한다.
#:
#: **토크는 전류에 단순 비례하지 않는다.** ROBOTIS 공식 성능그래프
#: (~/Downloads/xm430_w350_performance_graph.jpg) 를 보면 토크 0 에서도 전류가
#: 약 0.27 A 흐른다 — 마찰·철손으로 나가는 무부하 전류라 출력 토크를 안 만든다.
#: 그래서 τ = k·(I − I0) 다.
#:
#:   그래프 두 점  (τ 0.05, I 0.27) 과 (τ 3.05, I 1.80)
#:   k  = 3.00 / 1.53 = 1.96 N·m/A       I0 = 0.27 A
#:   검산: I = 2.3 A(스톨 규격) → τ = 1.96 × (2.3 − 0.27) = 3.98 ≈ 4.0  (규격 4.1 과 일치)
#:   700 틱: τ = 1.96 × (1.883 − 0.27) = **3.16 N·m**
#:
#: 처음엔 단순 비례로 4.1 × 1.883/2.3 = 3.36 을 썼는데 무부하 전류를 빠뜨린
#: 값이라 6 % 낙관적이었다 (2026-08-10 정정). 하필 그 6 % 가 실제 곡선이
#: 급격히 처지기 시작하는 구간이라, 낙관하면 v40 과 같은 종류의 갭이 남는다.
#:
#: 남은 알려진 낙관: DCMotor 는 **직선** 모델이라 그래프 끝의 처짐
#: (τ 3.05 에서 실제 ~5 RPM vs 직선 ~12 RPM) 을 못 그린다. effort_limit 을
#: 3.16 으로 잘라 그 구간에 거의 안 들어가게 두는 것으로 갈음한다.
XM430_CONT_TORQUE_700 = 3.16


def _dc_cfg(joint_names, effort_limit: float) -> DCMotorCfg:
    return DCMotorCfg(
        joint_names_expr=joint_names,
        stiffness=37.65,
        damping=1.352,
        armature=0.01432,
        friction=0.0761,
        saturation_effort=XM430_STALL_TORQUE,
        effort_limit=effort_limit,
        velocity_limit=XM430_NO_LOAD_SPEED,
    )


XM430_LEG_DC_CFG = _dc_cfg(_LEG_JOINT_NAMES, XM430_CONT_TORQUE_700)
XM430_HEAD_DC_CFG = _dc_cfg(_HEAD_JOINT_NAMES, XM430_CONT_TORQUE_700)

##
# Robot config
##

OPEN_DUCK_MINI_V2_CFG = ArticulationCfg(
    spawn=sim_utils.UsdFileCfg(
        usd_path=OPEN_DUCK_MINI_USD_PATH,
        activate_contact_sensors=True,
        rigid_props=sim_utils.RigidBodyPropertiesCfg(
            disable_gravity=False,
            retain_accelerations=False,
            linear_damping=0.0,
            angular_damping=0.0,
            max_linear_velocity=1000.0,
            max_angular_velocity=1000.0,
            max_depenetration_velocity=1.0,
        ),
        articulation_props=sim_utils.ArticulationRootPropertiesCfg(
            enabled_self_collisions=False,
            solver_position_iteration_count=4,
            solver_velocity_iteration_count=0,
        ),
    ),
    init_state=ArticulationCfg.InitialStateCfg(
        pos=(0.0, 0.0, SPAWN_BASE_HEIGHT),
        joint_pos=dict(READY_JOINT_POS),
        joint_vel={".*": 0.0},
    ),
    soft_joint_pos_limit_factor=0.95,
    actuators={
        "legs": XM430_LEG_CFG,
        "head": XM430_HEAD_CFG,
    },
)

#: 위와 **액추에이터 모델만** 다른 로봇. 나머지(USD, 질량, init_state, 접촉센서,
#: soft_joint_pos_limit_factor)는 전부 같으므로 비교가 성립한다.
OPEN_DUCK_MINI_V2_DC_CFG = OPEN_DUCK_MINI_V2_CFG.replace(
    actuators={
        "legs": XM430_LEG_DC_CFG,
        "head": XM430_HEAD_DC_CFG,
    },
)
